#!/bin/sh                                          

# Additional options that are passed to mosquitto
OPTIONS="-d"

case "$1" in
    start)
	printf "Starting mosquitto: "
	start-stop-daemon -S -q -p /var/run/mosquitto.pid --exec /usr/sbin/mosquitto -- $OPTIONS
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
    stop)
	printf "Stopping mosquitto: "
	start-stop-daemon -K -q -p /var/run/mosquitto.pid
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
    restart)
	$0 stop
	$0 start
	;;
    *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
	;;
esac

