#!/bin/sh
#
# Custom script to be called by the Mender client when a new artifact
# is available for download.  This can be used to demonstrate state
# scripting by the user manually creating files in /tmp.
#
# Thanks to Drew Moseley (https://github.com/drewmoseley/meta-dmoseley-local-config/blob/master/mender-demo/recipes-mender/example-state-scripts/files/Download_Enter_00).

log() {
    echo "stderr:$*" >&2
}

log "$(cat /etc/mender/artifact_info): $(basename "$0") was called!"

RC=0
if [ -e /tmp/download-script-active ]; then
    while true; do
        log "Checking for files in /tmp"
        if [ -e /tmp/allow-download ]; then
            log "Found /tmp/allow-download"
            RC=0
            break
        elif [ -e /tmp/disallow-download ]; then
            log "Found /tmp/disallow-download"
            RC=1
            break
        else
            sleep 5
        fi
    done
fi

log "Returning $RC from $0 state script"
exit $RC
